apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-resored
spec:
  storageClassName: storage-class
  dataSource: 
    name: volumesnapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
