apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservicebg
  labels:
    app: paymentservicebg
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservicebg
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  template:
    metadata:
      labels:
        app: paymentservicebg
    spec:
      containers:
        - name: server
          image: "dmizverev/otus-paymentservice:0.0.2"