apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservicereverse
  labels:
    app: paymentservicereverse
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservicereverse
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: paymentservicereverse
    spec:
      containers:
        - name: server
          image: "dmizverev/otus-paymentservice:0.0.2"