prometheus:
  additionalServiceMonitors:
    - name: infra
      selector:
        matchExpressions:
          - key: app
            operator: In
            values: [elasticsearch-exporter, nginx-ingress]
      namespaceSelector:
        any: true
      endpoints:
        - path: /metrics
          port: metrics
        - path: /metrics
          port: http
grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.34.66.61.20.xip.io
    annotations: {
      kubernetes.io/ingress.class: nginx
    }
    path: /
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
additionalPrometheusRulesMap:
  elasticsearch-alertmanager.rules:
    groups:
      - name: elasticsearch
        rules:
          - alert: ElasticsearchTooFewNodesRunning
            expr: elasticsearch_cluster_health_number_of_nodes < 3
            for: 5m
            labels:
              severity: critical
            annotations:
              message: Running only {{$value}} ElasticSearch nodes.
              summary: ElasticSearch running less than 3 nodes
