apiVersion: v1
kind: Pod
metadata:
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: "dmizverev/otus-frontend:1.0.0"
    name: frontend
  dnsPolicy: ClusterFirst
  restartPolicy: Never
