apiVersion: v1
kind: Pod
metadata:
  name: otus-webapp
  labels:
    app: "web"
spec:
  initContainers:
    - name: intro
      image: busybox:1.31.1
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
        - name: app
          mountPath: /app
  containers:
    - name: web
      image: "dmizverev/otus-webapp:1.0.0"
      volumeMounts:
        - name: app
          mountPath: /app
  volumes:
    - name: app
      emptyDir: {}